name: Test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: sudo -E bash ./test.sh
        env:
          ORGANIZATION_URL: ${{ secrets.ORGANIZATION_URL }}
          RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }}
